apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: wiz-app
type: Opaque
stringData:
  mongodb-uri: mongodb://root:REPLACE_WITH_PASSWORD@mongodb-service:27017/tododb?authSource=admin