apiVersion: v1
kind: secret
metadata:
  name: mongodb-secret
  namespace: wiz-app
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: password
  mongodb-uri: mongodb://admin:password@mongodb-service:27017/tododb?authSource=admin