apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: wiz-app
type: Opaque
stringData:
  mongodb-uri: mongodb://admin:REPLACE_WITH_PASSWORD@wiz-mongodb-vm.us-west1-a.c.clgcporg10-151.internal:27017/tododb?authSource=admin

  